const { GoogleGenerativeAI } = require('@google/generative-ai');
const axios = require('axios');
const slugify = require('slugify');
const pool = require('../config/db');

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });

// ─── Fetch top news headlines ─────────────────────────────────────────────────
async function fetchTopNews(count = 2) {
    try {
        const response = await axios.get('https://newsapi.org/v2/top-headlines', {
            params: {
                language: 'en',
                pageSize: 10,
                apiKey: process.env.NEWS_API_KEY,
            },
            timeout: 10000,
        });

        const articles = response.data.articles
            .filter(a => a.title && a.description && !a.title.includes('[Removed]'))
            .slice(0, count);

        return articles;
    } catch (error) {
        console.error('[AI Blogger] Failed to fetch news:', error.message);
        return [];
    }
}

// ─── Generate a full blog post using Gemini ───────────────────────────────────
async function generateBlogFromNews(article) {
    const prompt = `
You are an expert blog writer. Based on this news headline, write a comprehensive, engaging blog post.

NEWS HEADLINE: "${article.title}"
NEWS DESCRIPTION: "${article.description}"
SOURCE: ${article.source?.name || 'News'}
DATE: ${new Date().toDateString()}

Write a detailed, informative blog post. Return ONLY a valid JSON object (no markdown, no code blocks) with these exact fields:
{
  "title": "engaging SEO-friendly blog post title (different from the headline, more creative)",
  "content": "full HTML blog post content with proper h2, h3, p, ul, li tags - minimum 600 words - include an introduction, main sections with subheadings, analysis, and conclusion",
  "meta_title": "SEO meta title (max 60 characters)",
  "meta_description": "SEO meta description (max 160 characters, compelling summary)",
  "category_suggestion": "one of: Technology, Business, Health, Science, Sports, Entertainment, Politics, World"
}

Make the content expert-level, informative, and engaging. Do NOT mention that it was generated by AI.
    `.trim();

    try {
        const result = await model.generateContent(prompt);
        const text = result.response.text();

        // Strip any accidental markdown code fences
        const cleaned = text.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
        const parsed = JSON.parse(cleaned);

        return parsed;
    } catch (error) {
        console.error('[AI Blogger] Gemini generation failed:', error.message);
        return null;
    }
}

// ─── Find or create a category in DB ─────────────────────────────────────────
async function getOrCreateCategory(categoryName) {
    try {
        const [existing] = await pool.query('SELECT id FROM categories WHERE name = ?', [categoryName]);
        if (existing.length) return existing[0].id;

        const slug = slugify(categoryName, { lower: true, strict: true });
        const [result] = await pool.query(
            'INSERT INTO categories (name, slug) VALUES (?, ?)',
            [categoryName, slug]
        );
        return result.insertId;
    } catch (error) {
        console.error('[AI Blogger] Category error:', error.message);
        return null;
    }
}

// ─── Find the admin user to assign as author ──────────────────────────────────
async function getAdminUserId() {
    try {
        const [users] = await pool.query("SELECT id FROM users WHERE role = 'admin' LIMIT 1");
        return users.length ? users[0].id : 1;
    } catch {
        return 1;
    }
}

// ─── Save generated blog as a draft ──────────────────────────────────────────
async function saveDraftPost(blogData, authorId, categoryId) {
    try {
        let slug = slugify(blogData.title, { lower: true, strict: true });

        // Ensure unique slug
        const [existing] = await pool.query('SELECT id FROM posts WHERE slug = ?', [slug]);
        if (existing.length) {
            slug = `${slug}-${Date.now()}`;
        }

        const [result] = await pool.query(
            `INSERT INTO posts 
             (title, slug, content, category_id, author_id, meta_title, meta_description, status, view_count) 
             VALUES (?, ?, ?, ?, ?, ?, ?, 'draft', 0)`,
            [
                blogData.title,
                slug,
                blogData.content,
                categoryId,
                authorId,
                blogData.meta_title || blogData.title.substring(0, 60),
                blogData.meta_description || '',
            ]
        );

        console.log(`[AI Blogger] ✅ Draft saved: "${blogData.title}" (ID: ${result.insertId})`);
        return result.insertId;
    } catch (error) {
        console.error('[AI Blogger] Failed to save draft:', error.message);
        return null;
    }
}

// ─── Main orchestrator: run the full AI blog generation pipeline ──────────────
async function runAIBlogger(postsToGenerate = 2) {
    console.log(`[AI Blogger] 🚀 Starting — generating ${postsToGenerate} blog drafts...`);

    const news = await fetchTopNews(postsToGenerate);
    if (!news.length) {
        console.log('[AI Blogger] ⚠️  No news fetched. Skipping.');
        return { success: false, generated: 0 };
    }

    const authorId = await getAdminUserId();
    let generatedCount = 0;

    for (const article of news) {
        console.log(`[AI Blogger] 📰 Processing: "${article.title}"`);

        const blogData = await generateBlogFromNews(article);
        if (!blogData) {
            console.log('[AI Blogger] ⚠️  Skipping article — generation failed.');
            continue;
        }

        const categoryId = await getOrCreateCategory(
            blogData.category_suggestion || 'World'
        );

        const postId = await saveDraftPost(blogData, authorId, categoryId);
        if (postId) generatedCount++;

        // Small delay between Gemini calls to avoid rate limiting
        if (news.indexOf(article) < news.length - 1) {
            await new Promise(resolve => setTimeout(resolve, 3000));
        }
    }

    console.log(`[AI Blogger] 🎉 Done — ${generatedCount} draft(s) created.`);
    return { success: true, generated: generatedCount };
}

module.exports = { runAIBlogger };
